version: "3.9"

volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      PORT: 51821
      HOST: 0.0.0.0
      INSECURE: "true"
      WG_PRE_UP: 'iptables -t nat -F; iptables -F;'
      WG_DEFAULT_DNS: 192.168.0.1      # DNS pushed to clients
      WG_HOST: vpn.jdlab.us
      WG_DEVICE: eth0
      WG_ALLOWED_IPS: |  # DNS servers should be allowed. You can use "0.0.0.0/0,::/0" instead
        1.1.1.1,8.8.8.8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7
        # Replace with your public IP or DDNS
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"   # WireGuard VPN
      - "51821:51821/tcp"   # Web UI
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
